### ISSUE TITLE
Example Crashes on npm start

### ISSUE THREAD

**Issue by peterbsmyth** [combine/universal-react-redux#16]
Here's the attached log

```
➜  react-redux-starter git:(master) npm start

> react-redux-starter@1.0.0 start /Users/Peter/code/community/react-redux-starter
> npm run build:development && npm run start:development


> react-redux-starter@1.0.0 build:development /Users/Peter/code/community/react-redux-starter
> $(npm bin)/webpack --progress --colors --display-error-details --config webpack/config.development.js

Hash: e43d9fd4afc3baa58ff4
Version: webpack 1.13.1
Time: 12242ms
                                 Asset      Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot   20.1 kB          [emitted]
448c34a56d699c29117adc64c43affeb.woff2     18 kB          [emitted]
 fa2772327f55d8198301fdb8bcfc8158.woff   23.4 kB          [emitted]
  e18bbf611f2a2e43afc071aa2f4e1512.ttf   45.4 kB          [emitted]
  89889688147bd7575d6327160d64e760.svg    109 kB          [emitted]
                             bundle.js   1.55 MB       0  [emitted]  main
                            styles.css    152 kB       0  [emitted]  main
                         bundle.js.map   1.91 MB       0  [emitted]  main
                        styles.css.map  87 bytes       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 913 hidden modules
Child extract-text-webpack-plugin:
        + 7 hidden modules

> react-redux-starter@1.0.0 start:development /Users/Peter/code/community/react-redux-starter
> npm run start:development:client & npm run start:development:server


> react-redux-starter@1.0.0 start:development:server /Users/Peter/code/community/react-redux-starter
> $(npm bin)/nodemon server


> react-redux-starter@1.0.0 start:development:client /Users/Peter/code/community/react-redux-starter
> node webpack/config.development.hot

Firing up Wepback dev server...
🚧 Webpack client dev-server listening on http://localhost:3001 with publicPath:http://localhost:3001/dist/
[nodemon] 1.9.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: server/**/*.js server/**/*.json common/layouts/server.html
[nodemon] starting `node server`
module.js:442
    throw err;
    ^

Error: Cannot find module '../webpack/config.dev'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function._module3.default._resolveFilename (/Users/Peter/code/community/react-redux-starter/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:403:34)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (config.js:4:21)
    at Module._compile (module.js:541:32)
    at loader (/Users/Peter/code/community/react-redux-starter/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Peter/code/community/react-redux-starter/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:458:32)
[nodemon] app crashed - waiting for file changes before starting...
Time: 8219ms
                                 Asset     Size  Chunks             Chunk Names
  f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
  e18bbf611f2a2e43afc071aa2f4e1512.ttf  45.4 kB          [emitted]
 fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
  89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                             bundle.js  2.28 MB       0  [emitted]  main
webpack: bundle is now VALID.
^C
```

**Comment by calvinl** [comment]
@peterbsmith2 is this from the master branch?

**Comment by peterbsmyth** [comment]
Yeah, literally git clone, npm install, npm start

On Friday, June 17, 2016, Calvin Lai notifications@github.com wrote:

> @peterbsmith2 https://github.com/peterbsmith2 is this from the master
> branch?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/combine/react-redux-starter/issues/16#issuecomment-226871656,
> or mute the thread
> https://github.com/notifications/unsubscribe/AB39ohQh99mtY_Ph9E5GVAIS5sVHHmjzks5qMwFkgaJpZM4I4seT
> .

## 

Sent from Gmail Mobile

**Comment by calvinl** [comment]
@peterbsmith2 what is your `NODE_ENV` set to?

**Comment by calvinl** [comment]
to be clear, it should be `development` or `production`, not `dev`

**Comment by peterbsmyth** [comment]
That's the issue. Almost guaranteed. I'll let you know in an hour

On Friday, June 17, 2016, Calvin Lai notifications@github.com wrote:

> to be clear, it should be development or production, not dev
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/combine/react-redux-starter/issues/16#issuecomment-226872871,
> or mute the thread
> https://github.com/notifications/unsubscribe/AB39opMHk4YfXQ4T4VRefL88jYFURTruks5qMwK9gaJpZM4I4seT
> .

## 

Sent from Gmail Mobile

**Comment by calvinl** [comment]
@peterbsmith2 I've updated the run scripts to force `NODE_ENV=development` in master. I'm closing this for now, feel free to reopen if you still have issues.
