### ISSUE TITLE
MissingEnvVarsError on yarn start

### ISSUE THREAD

**Issue by alex-golovanov** [combine/universal-react-redux#32]
```
yarn start v0.27.5
$ better-npm-run dev:build && better-npm-run dev:start
running better-npm-run in /Users/alexandergolovanov/Node/universal-react-redux
Executing script: dev:build

to be executed: yarn run babel-node -- ./script/build webpack/development.js 

/Users/alexandergolovanov/Node/universal-react-redux/node_modules/dotenv-safe/index.js:37
            throw new MissingEnvVarsError(allowEmptyValues, options.path || '.env', sample, missing, dotenvResult.error);
            ^
MissingEnvVarsError: The following variables are defined in .env.example but are not defined in the environment: APPLICATION_PORT, ASSET_HOST, WEBPACK_OUTPUT_PATH, DEV_SERVER_PORT, DEV_SERVER_HOSTNAME.
Make sure to add them to .env or directly to the environment.
If you expect any of these missing variables to be empty, you can use the allowEmptyValues option: 

require('dotenv-safe').load({
  allowEmptyValues: true
});
Also, the following error was thrown when trying to read variables from .env: ENOENT: no such file or directory, open '.env'
    at Object.config (/Users/alexandergolovanov/Node/universal-react-redux/node_modules/dotenv-safe/index.js:37:19)
    at Object.<anonymous> (/Users/alexandergolovanov/Node/universal-react-redux/webpack/base.js:1:24)
    at Module._compile (module.js:569:30)
    at loader (/Users/alexandergolovanov/Node/universal-react-redux/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alexandergolovanov/Node/universal-react-redux/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

And then with `allowEmptyValues: true`

```
yarn start v0.27.5
$ better-npm-run dev:build && better-npm-run dev:start
running better-npm-run in /Users/alexandergolovanov/Node/universal-react-redux
Executing script: dev:build

to be executed: yarn run babel-node -- ./script/build webpack/development.js 

/Users/alexandergolovanov/Node/universal-react-redux/node_modules/dotenv-safe/index.js:37
            throw new MissingEnvVarsError(allowEmptyValues, options.path || '.env', sample, missing, dotenvResult.error);
            ^
MissingEnvVarsError: The following variables are defined in .env.example but are not defined in the environment: APPLICATION_PORT, ASSET_HOST, WEBPACK_OUTPUT_PATH, DEV_SERVER_PORT, DEV_SERVER_HOSTNAME.
Make sure to add them to .env or directly to the environment.
Also, the following error was thrown when trying to read variables from .env: ENOENT: no such file or directory, open '.env'
    at Object.config (/Users/alexandergolovanov/Node/universal-react-redux/node_modules/dotenv-safe/index.js:37:19)
    at Object.<anonymous> (/Users/alexandergolovanov/Node/universal-react-redux/webpack/base.js:1:24)
    at Module._compile (module.js:569:30)
    at loader (/Users/alexandergolovanov/Node/universal-react-redux/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/alexandergolovanov/Node/universal-react-redux/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
error Command failed with exit code 1.
```

**Comment by calvinl** [comment]
@pr0digy This should do the trick:

```
cp .env.example .env
```

I should update the docs. If you have a moment, you could submit a PR. Thanks!

**Comment by alex-golovanov** [comment]
Yes, that worked out just fine, thanks. I've updated the docs and submitted a pull request.
