### ISSUE TITLE
Unable to start application using yarn start

### ISSUE THREAD

**Issue by mkrishna2025** [combine/universal-react-redux#55]
C:\Research\GIT\Public\universal-react-redux>yarn start
yarn start v0.27.5
$ better-npm-run dev:start
running better-npm-run in C:\Research\GIT\Public\universal-react-redux
Executing script: dev:start

to be executed: "npm run dev:start:client & npm run dev:start:server"

> universal-react-redux@7.0.0 dev:start:client C:\Research\GIT\Public\universal-react-redux
> better-npm-run dev:start:client

running better-npm-run in C:\Research\GIT\Public\universal-react-redux
Executing script: dev:start:client

to be executed: "npx babel-node webpack/development.client.babel"
npx: installed 1 in 9.304s
Path must be a string. Received undefined
C:\Research\GIT\Public\universal-react-redux\node_modules\babel-cli\bin\babel-node.js
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:489:7)
    at Object.<anonymous> (C:/Research/GIT/Public/universal-react-redux/webpack/base.js:78:16)
    at Module._compile (module.js:652:30)
    at loader (C:\Research\GIT\Public\universal-react-redux\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Research\GIT\Public\universal-react-redux\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-react-redux@7.0.0 dev:start:client: `better-npm-run dev:start:client

**Comment by calvinl** [comment]
@mkrishna2025 Have you followed the section in the [README](https://github.com/combine/universal-react-redux/blob/master/README.md#development-mode) to copy the example env file?

**Comment by calvinl** [comment]
@mkrishna2025 Closing due to inactivity and I suspect you hadn't copied the .env file over. Please feel free to reopen if you still have issues.
