### ISSUE TITLE
After clean install, cannot find module 'kind-of'

### ISSUE THREAD

**Issue by hartym** [combine/universal-react-redux#8]
First install, followed instructions. When `npm start`, I first got:

`Error: Cannot find module 'kind-of'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/rd/Sites/lc2/react-redux-starter/node_modules/is-number/index.js:10:14)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)`

Then, I did `npm i kind-of --save`, and the error went away.

No idea if it should be dev or non dev dependency, and whether or not there is something specific about my setup, so instead of proposing a package.json patch myself, I let you decide having the overall information what is to be done.

TY.

**Comment by calvinl** [comment]
That's odd. I'll take a look at it. It looks like there's another module that depends on it (`is-number`) and it can't find the dependency.

**Comment by ChrisCooney** [comment]
Did this get resolved?

**Comment by calvinl** [comment]
@ChrisCooney it should be -- are you having an issue?
